scrape_configs:
  - job_name: cubejs
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.173.241:4000'] # replace with your host ip